runtime:
  - Runtime:
      class: ru.taskurotta.example.bootstrap.SimpleRuntimeConfig
      instance:
        context: "fff"

spreader:
  - Spreader:
      class: ru.taskurotta.example.bootstrap.SimpleSpreaderConfig
      instance:
        endpoint: "http://localhost:8082"
        threadPoolSize: 10
        readTimeout: 0
        connectTimeout: 3000

profiler:
  - Profiler:
      class: ru.taskurotta.bootstrap.config.DefaultProfilerConfig
      instance:
        class: ru.taskurotta.bootstrap.profiler.MetricsProfiler
        properties:
          meterCycle: true
          trackExecute: true
          trackCycle: true
          trackPull: true
          trackRelease: true
          trackError: false
          logOutput: false
          consoleOutput: false

actor:
  - ProfileService:
      actorInterface: ru.taskurotta.example.worker.profile.UserProfileService
      runtimeConfig: Runtime
      spreaderConfig: Spreader
      profilerConfig: Profiler
      count: 1

  - MailService:
      actorInterface: ru.taskurotta.example.worker.mail.MailService
      runtimeConfig: Runtime
      spreaderConfig: Spreader
      profilerConfig: Profiler
      count: 1

  - SMSService:
      actorInterface: ru.taskurotta.example.worker.sms.SMSService
      runtimeConfig: Runtime
      spreaderConfig: Spreader
      profilerConfig: Profiler
      count: 1
logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%c - \%m\%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: ./target/logs/actors.log
             append: false
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: INFO
        - org:
             key: name
             \@level: ERROR
        - httpclient:
             key: name
             \@level: ERROR
    root:
        appender-ref:
            - STDOUT:
                key: ref
            - FILE:
                key: ref

